给定一个向量，让向量中每一个ele乘上2

对于python原生list：

In [45]:
n = 5
L = [i for i in range(n)]

In [46]:
L * 2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [47]:
A = []
for e in range(n):
    A.append(2*e)
A

[0, 2, 4, 6, 8]

In [48]:
n = 1000000
L = [i for i in range(n)]

In [49]:
%%time
A = []
for e in range(n):
    A.append(2*e)
A

CPU times: user 131 ms, sys: 12.5 ms, total: 144 ms
Wall time: 143 ms


In [50]:
%%time
A = [2*e for e in L]

CPU times: user 52 ms, sys: 7.31 ms, total: 59.3 ms
Wall time: 58 ms


In [51]:
import numpy as np
L = np.arange(n)
L

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [52]:
%%time 
A = np.array(2*e for e in L)

CPU times: user 16 µs, sys: 1 µs, total: 17 µs
Wall time: 17.9 µs


In [53]:
A

[0, 2, 4, 6, 8]

In [54]:
%%time
A = 2 * L
A

CPU times: user 2.73 ms, sys: 3.26 ms, total: 5.98 ms
Wall time: 4.81 ms


In [55]:
A

[0, 2, 4, 6, 8]

### Universal Function

In [57]:
X = np.arange(1, 16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [58]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [59]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [60]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [62]:
X // 2 #不会舍去，而是进一

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [63]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [64]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [65]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [66]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [67]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [68]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [69]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [74]:
np.exp(X) #e^X

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [77]:
np.power(3, X) #3^X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [78]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [79]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [80]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [81]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [83]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [85]:
B = np.full((2,2), fill_value = 10)
B

array([[10, 10],
       [10, 10]])

In [86]:
A + B

array([[10, 11],
       [12, 13]])

In [87]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [88]:
A * B

array([[ 0, 10],
       [20, 30]])

In [89]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [90]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [91]:
A

array([[0, 1],
       [2, 3]])

In [92]:
A.T

array([[0, 2],
       [1, 3]])

In [93]:
C = np.full((3,3), fill_value = 100)

In [94]:
A.dot(C)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

### 向量与矩阵的运算

In [95]:
v = np.array([1,2])

In [96]:
A

array([[0, 1],
       [2, 3]])

In [97]:
v + A #数学上没有意义，但是向量会与矩阵的每一样做加法

array([[1, 3],
       [3, 5]])

In [98]:
v - A

array([[ 1,  1],
       [-1, -1]])

In [99]:
v * A

array([[0, 2],
       [2, 6]])

In [112]:
(v * A.T).T

array([[0, 1],
       [4, 6]])

In [101]:
np.vstack([v] * 2)

array([[1, 2],
       [1, 2]])

In [104]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [105]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [106]:
np.tile(v, (2,1))

array([[1, 2],
       [1, 2]])

In [107]:
np.tile(v, (2,1)) + A

array([[1, 3],
       [3, 5]])

In [108]:
v.dot(A)

array([4, 7])

In [110]:
A.dot(v)

array([2, 8])

### 矩阵的逆

In [113]:
A

array([[0, 1],
       [2, 3]])

In [117]:
invA = np.linalg.inv(A)

In [118]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [119]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [122]:
X = np.arange(16).reshape(2,8)

In [123]:
invX = np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [124]:
pinvX = np.linalg.pinv(X)

In [127]:
pinvX.shape

(8, 2)

In [125]:
X.dot(pinvX) 

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [126]:
pinvX.dot(X) #不能这么算

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02,  3.05311332e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02,  2.22044605e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-8.32667268e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952