In [1]:
import numpy as np
x = np.random.normal(0, 1, size = 1000000)

### np.argmin(), np.argmax()

In [2]:
np.min(x)

-4.612576887239997

In [3]:
np.argmin(x)

117512

In [4]:
x[117512]

-4.612576887239997

In [5]:
x[np.argmin(x)]

-4.612576887239997

In [6]:
np.max(x)

4.941481949753744

In [8]:
x[np.argmax(x)]

4.941481949753744

### sorting and indexing

In [10]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
np.random.shuffle(x) #打乱顺序
x

array([13,  4, 10, 14,  2, 15,  7,  5,  9, 12,  6,  1,  0,  3, 11,  8])

In [12]:
np.sort(x) #返回排好序的向量，但是x没有被改变！！

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
x

array([13,  4, 10, 14,  2, 15,  7,  5,  9, 12,  6,  1,  0,  3, 11,  8])

In [14]:
x.sort() #这一句才是对x进行了改变！！

In [15]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
X = np.random.randint(10, size = (4,4)) #【0，10）之间去整数随机数
X

array([[8, 8, 6, 5],
       [5, 5, 1, 8],
       [0, 0, 4, 5],
       [9, 5, 3, 3]])

In [22]:
np.sort(X, axis = 0) #这里注意 因为X不是向量，而是矩阵，axis = 0来sort。 
#想象着一横行 里面 有四个人，每个人的任务就是将自己这一列的元素排序。

array([[0, 0, 1, 3],
       [5, 5, 3, 5],
       [8, 5, 4, 5],
       [9, 8, 6, 8]])

In [23]:
np.sort(X, axis = 1) #这里注意 因为X不是向量，而是矩阵，axis = 1来sort。 
#想象着一竖列 里面 有四个人，每个人的任务就是将自己这一行的元素排序。

array([[5, 6, 8, 8],
       [1, 5, 5, 8],
       [0, 0, 4, 5],
       [3, 3, 5, 9]])

In [29]:
np.sort(X) #注意！！ 默认axis = 1
#np.concatenate() 默认axis = 0
#这里np.sort()默认axis = 1
#np.sum() 没有默认axis = 几，因为np.sum()是全部ele相加

array([[5, 6, 8, 8],
       [1, 5, 5, 8],
       [0, 0, 4, 5],
       [3, 3, 5, 9]])

In [28]:
np.sum(X)

75

In [30]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
np.random.shuffle(x) #这个就是真的将x打乱了！ 注意:np.sort(x) 没有将x改变，将x改变的是x.sort()

In [32]:
x

array([ 0, 10, 14,  4,  2, 11,  6,  7,  9,  3,  5,  1,  8, 12, 15, 13])

In [33]:
np.argsort(x) #第一小的元素，在0位置，第二小的元素，在11位置。

array([ 0, 11,  4,  9,  3, 10,  6,  7, 12,  8,  1,  5, 13, 15,  2, 14])

In [40]:
y = np.arange(3,13)
y

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
np.random.shuffle(y)
y

array([10, 12,  9,  5,  3, 11,  4,  8,  6,  7])

In [55]:
np.partition(y, 5) #这里的参数5是指 y 排序好之后，里面index == 5，也就是第六个元素：9. 9左边的元素都比9小，但是是稳定排序

array([ 4,  3,  6,  5,  7,  8,  9, 10, 12, 11])

In [56]:
np.argpartition(y, 5) #这里说的是，第0个元素也就是y中index==6的元素，是np.partition(y, 5)中最小的元素。

array([6, 4, 8, 3, 9, 7, 2, 0, 1, 5])

In [57]:
y #np.partition()没有改变y，y依旧是乱序。

array([10, 12,  9,  5,  3, 11,  4,  8,  6,  7])

In [58]:
X

array([[8, 8, 6, 5],
       [5, 5, 1, 8],
       [0, 0, 4, 5],
       [9, 5, 3, 3]])

In [59]:
np.argsort(X, axis = 1) #这个是按行排序，但是返回的是index

array([[3, 2, 0, 1],
       [2, 0, 1, 3],
       [0, 1, 2, 3],
       [2, 3, 1, 0]])

In [60]:
np.argsort(X, axis = 0) #这个是按列排序，但是返回的是index

array([[2, 2, 1, 3],
       [1, 1, 3, 0],
       [0, 3, 2, 2],
       [3, 0, 0, 1]])

In [65]:
np.partition(X, 2, axis = 1) #按行：第一行第三大（index == 2意味着排序后第三大）是8
#第二行第三大（index == 2意味着排序后第三大）是5

array([[5, 6, 8, 8],
       [1, 5, 5, 8],
       [0, 0, 4, 5],
       [3, 3, 5, 9]])

In [66]:
np.argpartition(X, 2, axis = 1)

array([[3, 2, 1, 0],
       [2, 1, 0, 3],
       [0, 1, 2, 3],
       [2, 3, 1, 0]])

In [62]:
np.argpartition(X, 2, axis = 0)

array([[2, 2, 1, 3],
       [1, 1, 3, 2],
       [0, 3, 2, 0],
       [3, 0, 0, 1]])