In [25]:
import numpy as np
import matplotlib as plt
from sklearn import datasets

In [26]:
iris = datasets.load_iris()

In [27]:
X = iris.data
y = iris.target

In [28]:
X.shape

(150, 4)

In [29]:
y.shape

(150,)

### train_test_split
将X拆分成：训练数据集 + 测试数据集

之前是将X全部当成训练数据集

In [30]:
y #y是排好序的，所以不能直接选取y的前120个数据。因为这样就会遗漏label == 2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

1. 需要shuffle

2. 但是X和y是一一对应的，不能分开shuffle

3. 所以方法一：将X，y合在一起，shuffle，最后将二者分离

4. 方法二：对index进行shuffle

In [31]:
shuffle_indexes = np.random.permutation(len(X))  #从0-n的数的随机排列。

In [32]:
shuffle_indexes

array([ 70,  11,  73, 132,  42,  33, 119,  76,  82,  88, 103,  14,  99,
        68,   7,  19,  87, 102,  27,  12, 144, 128,  47,   6,  28,  17,
        54,  78,  57,  98,  51, 123, 107, 108, 134, 130,  43,   3, 135,
       136,  67,  36, 106,  49, 145, 140,  72, 110,  13,  92, 141,  32,
        48,  83, 133, 120,   1,  35, 129,  84,  96, 100,   2,  25,  29,
        53,  95,  85,  66, 101,  79,  23, 124,   0,  77,   8, 114,   5,
       137,  65, 149,  74, 126,  39,  31, 112,  60,  93,  15,  81, 104,
       146, 105,  59, 142,  64,  69,  75, 122,  40,  55, 147,  20, 109,
         4,  52,  62,  45, 143,  46, 131,  50,  30,  61, 121,  16, 148,
        86, 116,  38,  97, 115,  91,  22, 111,  90,   9,  21,  80, 117,
        44,  18,  34,  89,  58,  71,  26, 125,  63,  41,  37, 118,  56,
        94,  10, 138, 113, 139, 127,  24])

In [33]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio) #防止乘完之后是浮点数

In [34]:
test_size

30

In [35]:
#前20%是测试，后20%是训练。你也可以交换顺序
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [36]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [37]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [38]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### use our model_selection.py

In [39]:
import sys
sys.path.append("..") #因为model_selection.py 在myML文件夹，而myML文件夹在jupyterNB的上层，所以用”..“
from myML.model_selection import my_train_test_split #from .py import func()

In [40]:
X_train, X_test, y_train, y_test = my_train_test_split(X, y)

In [41]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [46]:
import sys
sys.path.append("..") #因为model_selection.py 在myML文件夹，而myML文件夹在jupyterNB的上层，所以用”..“
from myML.matrics import accuracy_score
from myML.kNN_classifier import myKNNClassifier #from .py import class
 #from .py import class

In [47]:
myKnnClf = myKNNClassifier(k=3)

In [48]:
myKnnClf.fit(X_train, y_train)

Bessie: from __repr__: KNN(k = 3)

In [49]:
y_predict = myKnnClf.predict(X_test)
y_predict

array([1, 2, 1, 2, 2, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 0, 2, 1, 1, 0, 2, 2,
       2, 2, 0, 0, 1, 1, 2, 1])

### 预测准确率

In [50]:
np.sum(y_predict == y_test)

30

In [51]:
np.sum(y_predict == y_test) / len(y_test)

1.0

### sklearn中内置train_test_split

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 921) #随机种子random_state

In [45]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)
