In [6]:
import numpy as np
import matplotlib as plt
from sklearn import datasets

In [7]:
iris = datasets.load_iris()

In [8]:
X = iris.data
y = iris.target

In [9]:
X.shape

(150, 4)

In [10]:
y.shape

(150,)

### train_test_split
将X拆分成：训练数据集 + 测试数据集

之前是将X全部当成训练数据集

In [11]:
y #y是排好序的，所以不能直接选取y的前120个数据。因为这样就会遗漏label == 2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

1. 需要shuffle

2. 但是X和y是一一对应的，不能分开shuffle

3. 所以方法一：将X，y合在一起，shuffle，最后将二者分离

4. 方法二：对index进行shuffle

In [12]:
shuffle_indexes = np.random.permutation(len(X))  #从0-n的数的随机排列。

In [13]:
shuffle_indexes

array([ 62,  87,  88,  29, 119,  43,  93,  16, 116,  17,   0,  32,  57,
       138,  50,  85, 136,  86, 101,  90,  21,  33, 125,  82, 133,  35,
       147,  24,  96, 124,  20, 107,  76, 114, 110,  92, 115, 123,  39,
       135,  69,  58,  46, 142,  74, 149, 140, 129,  55,  18,  67,  79,
        71, 139, 122,  36, 146,  70,   7, 103,  73, 134, 128,  89, 104,
       127, 120, 117,  81,  34,  91, 143,  14,  66,  54, 145,  56,   8,
       111, 130, 126,  61,  63,   3, 132, 137,  97,  98,  94,  75, 121,
         6, 112,  28, 109,  59, 148,   4,  49,  51,  99,  42,  53,  40,
        13,  11, 102,  19, 100,  72,  68,  60, 113, 106,  31,   5, 131,
       105,   2,  22,  38,   9,  84,  52, 144,  12,  41,  78,  37,  80,
        15,  65,  47,  10,  26,  30,  95,  77,  64,  45,  44,   1, 118,
        23,  83,  25, 108,  48, 141,  27])

In [14]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio) #防止乘完之后是浮点数

In [15]:
test_size

30

In [16]:
#前20%是测试，后20%是训练。你也可以交换顺序
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [17]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [18]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [19]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### use our model_selection.py

In [20]:
from model_selection import my_train_test_split #from .py import func()

In [22]:
X_train, X_test, y_train, y_test = my_train_test_split(X, y)

In [23]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [24]:
from kNN_classifier import myKNNClassifier #from .py import class

In [25]:
myKnnClf = myKNNClassifier(k=3)

In [26]:
myKnnClf.fit(X_train, y_train)

Bessie: from __repr__: KNN(k = 3)

In [27]:
y_predict = myKnnClf.predict(X_test)
y_predict

array([0, 1, 2, 1, 2, 0, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 0, 2, 0, 1,
       1, 2, 2, 2, 2, 0, 2, 2])

### 预测准确率

In [28]:
np.sum(y_predict == y_test)

29

In [29]:
np.sum(y_predict == y_test) / len(y_test)

0.9666666666666667

### sklearn中内置train_test_split

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 921) #随机种子random_state

In [32]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)
