In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

## Python list的特点

虽然也可以表示多维数组，但是有缺点

In [3]:
L = [i for i in range(10)]

In [4]:
L[5]

5

In [5]:
L[5] = 100

In [6]:
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

python list中的元素的type可以是不一样的, 所以python list很灵活，但是效率低，需要检查每个ele的类型是什么

In [7]:
L[5] = "Bessie"

In [8]:
L

[0, 1, 2, 3, 4, 'Bessie', 6, 7, 8, 9]

 python 中也有限制数组类型的module，这叫array

In [9]:
 import array

### <font color="#dd0000"> array.array()  </font><br /> 

In [10]:
arr = array.array('i', [i for i in range(10)])

In [11]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

注意array.array()第一个参数'i'意思是array中都是int（整型）

In [12]:
arr[5] = "Bessie"

TypeError: an integer is required (got type str)

array module中没有相应运算，同时也不能支持矩阵表达和运算，所以numpy应运而生

### numpy.array

1. numpy.array会限制type，但是python list不会限制type但是效率低
2. numpy.array可以支持高维矩阵，支持运算

In [16]:
nparr = np.array([i for i in range(10)])

In [14]:
nparr[5] = "Bessie"

ValueError: invalid literal for int() with base 10: 'Bessie'

In [17]:
nparr.dtype

dtype('int64')

浮点数会implicitly类型转换成整型：

In [18]:
nparr[5] = 3.7

In [19]:
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

只要生成的时候有float，那么dtype就一直是float

In [20]:
nparr2 = np.array([1,2,3.0])

In [21]:
nparr2.dtype

dtype('float64')

### 其他创建numpy.array的方法

1. np.zeros()

2. np.ones()

3. np.full()

### np.zeros()

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros(10).dtype

dtype('float64')

In [24]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.zeros([3,5]) #默认是float

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros(shape = (3,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
np.zeros(shape = [3,5], dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### np.ones()

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.ones([3,5]) #默认是float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### np.full()

In [32]:
np.full((3,5), 66)  #默认是int

array([[66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66]])

In [33]:
np.full(shape = (3,5), fill_value = 66.)

array([[66., 66., 66., 66., 66.],
       [66., 66., 66., 66., 66.],
       [66., 66., 66., 66., 66.]])

### arange

In [36]:
[i for i in range(0, 20, 2)] #前闭后开：不包括20

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [35]:
[i for i in range(0, 1, 0.2)] #步长不能为浮点数

TypeError: 'float' object cannot be interpreted as an integer

In [37]:
np.arange(0, 20, 2) #前闭后开：不包括20

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
np.arange(0, 1, 0.2) #步长可以是浮点数

array([0. , 0.2, 0.4, 0.6, 0.8])

In [39]:
np.arange(0, 10) #默认步长是 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(10) #默认从0开始

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [41]:
np.linspace(0, 20, 10) #前闭后闭，步数为10

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [42]:
np.linspace(0, 20, 11) #前闭后闭，步数为11

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [43]:
np.random.randint(0, 10) #生成从0到10之间: [0, 10) 的随机数 

2

In [44]:
np.random.randint(0, 1, 10) #前闭后开，所以取不到1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
np.random.randint(4, 8, size = 10) #标注最后一个para是size

array([7, 6, 4, 5, 4, 7, 4, 5, 6, 4])

In [46]:
np.random.randint(4, 8, size = (3,5)) #(3,5)这个结构叫tuple，元组

array([[4, 5, 5, 5, 7],
       [7, 6, 4, 5, 7],
       [6, 6, 6, 5, 4]])

In [47]:
np.random.seed(666)

In [48]:
np.random.randint(4, 8, size = (3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [49]:
np.random.seed(666)
np.random.randint(4, 8, size = (3,5)) #随机代码是伪随机的，可控制的随机

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [50]:
np.random.random() #生成[0,1)之间的浮点数

0.2811684913927954

In [51]:
np.random.random(10) #生成10个[0,1)之间的浮点数

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [52]:
np.random.random([3,5]) #生成3x5个[0,1)之间的浮点数

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [53]:
np.random.normal() #标准正态分布

0.7760516793129695

In [54]:
np.random.normal(10, 100) #mean = 10, sigma^2 = 100

128.06359754812632

In [55]:
np.random.normal(0, 1, (3,5)) #mean = 0, sigma^2 = 1, size = (3,5)

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])

### notebook里面的文档查询：

In [56]:
np.random.normal?

In [57]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap