In [16]:
import numpy as np
import matplotlib.pyplot as plt

raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1] # 1 为恶性肿瘤

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514]) #我们要训练的

In [17]:
%run kNN.py

In [18]:
kNN_classify(6, X_train, y_train, x)

1

In [19]:
predict_y = kNN_classify(6, X_train, y_train, x)
predict_y

1

### 使用scikit-learn中的knn

In [20]:
from sklearn.neighbors import KNeighborsClassifier
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [21]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [22]:
kNN_classifier.predict(x) #Expected 2D array, got 1D array instead
#报错的原因：
#需要传入一个矩阵，之所以是矩阵，是因为sklearn认为我们要预测几个样本，所以希望我们将要预测的样本（一个样本是一个向量）整理成矩阵
#此例子虽然只有一个样本，但是也要转化成矩阵，用reshape()

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [23]:
x.shape #现在x还是向量

(2,)

In [26]:
x

array([8.09360732, 3.36573151])

In [24]:
X_predict = x.reshape(1, -1) #因为我们知道一共有一个样本，所以第一个参数是1
X_predict.shape #现在x是矩阵了，新的x叫做X_predict

(1, 2)

In [25]:
X_predict

array([[8.09360732, 3.36573151]])

In [27]:
y_predict = kNN_classifier.predict(X_predict)
y_predict

array([1])

In [28]:
y_predict[0] #取其中的第一个样本

1

### build our new KNN classifier

In [50]:
%run kNN_classifier.py

In [51]:
my_knnclf = myKNNClassifier(k = 6)

In [52]:
my_knnclf.fit(X_train, y_train)

Bessie: from __repr__: KNN(k = 6)

In [53]:
y_predict = my_knnclf.predict(X_predict)
y_predict

array([1])

In [54]:
y_predict[0]

1