In [1]:
import numpy as np
import matplotlib as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train_test_split
将X拆分成：训练数据集 + 测试数据集

之前是将X全部当成训练数据集

In [7]:
y #y是排好序的，所以不能直接选取y的前120个数据。因为这样就会遗漏label == 2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

1. 需要shuffle

2. 但是X和y是一一对应的，不能分开shuffle

3. 所以方法一：将X，y合在一起，shuffle，最后将二者分离

4. 方法二：对index进行shuffle

In [9]:
shuffle_indexes = np.random.permutation(len(X))  #从0-n的数的随机排列。

In [10]:
shuffle_indexes

array([ 73, 111,  18,  30,  38,  20,  89,  84, 132,   0, 148, 102,  72,
       113,  14, 107, 129,  42,  88,  15, 127, 126,  66,  79,  16,  63,
        40,  31,  91,   8,  26, 104,  45,  54,  94,  13, 138,  98,  99,
        95, 114,  65,  39, 119, 117, 103, 144,  25, 143,  74,   2,  52,
        82,  46, 139, 106, 120,  75,   3,  43, 133, 123,  32, 149,  71,
        93,  24,  78, 100,  44, 110,  92,  97, 124,  86,  29,   7, 112,
       122, 147,  81,  68, 101,  47,  11,   5, 141, 118,  50, 105, 108,
        28, 116,  85, 115,  19,  80,  22, 137,  67,  64,   6,  77, 128,
        62,  12,  37,  83,   1,  70,  33, 145, 121,  35,  59, 136, 135,
        23,  56,  61, 134, 142,  48, 125, 146,  96,  34,  17,  49,   4,
       130,  41,  87, 131,  90,  27,  69,  53,  76, 140,  10,   9,  36,
        57,  51, 109,  58,  60,  55,  21])

In [13]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio) #防止乘完之后是浮点数

In [14]:
test_size

30

In [16]:
#前20%是测试，后20%是训练。你也可以交换顺序
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [17]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [18]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [19]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### use our model_selection.py

In [22]:
from model_selection import train_test_split #from .py import func()

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [24]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [26]:
from kNN_classifier import myKNNClassifier #from .py import class

In [27]:
myKnnClf = myKNNClassifier(k=3)

In [28]:
myKnnClf.fit(X_train, y_train)

Bessie: from __repr__: KNN(k = 3)

In [31]:
y_predict = myKnnClf.predict(X_test)
y_predict

array([2, 0, 1, 2, 0, 1, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 2, 2, 0, 0, 0, 2,
       0, 0, 2, 1, 0, 1, 2, 0])

### 预测准确率

In [32]:
np.sum(y_predict == y_test)

29

In [33]:
np.sum(y_predict == y_test) / len(y_test)

0.9666666666666667

### sklearn中内置train_test_split

In [34]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)