In [2]:
import numpy as np

L = np.random.random(100)

In [3]:
L

array([0.68702496, 0.44934835, 0.97692072, 0.41407234, 0.27333634,
       0.71219955, 0.81806749, 0.78478934, 0.14065019, 0.83516384,
       0.8694099 , 0.65849521, 0.39745382, 0.14230116, 0.50386923,
       0.24309896, 0.62723339, 0.40293887, 0.79738918, 0.11382836,
       0.22771094, 0.17340446, 0.10390878, 0.70257552, 0.01691526,
       0.49279543, 0.03593871, 0.77595927, 0.10361789, 0.25348761,
       0.21402037, 0.04170315, 0.98660598, 0.32489002, 0.03663576,
       0.22439429, 0.44997978, 0.13710371, 0.75727434, 0.43120698,
       0.35604159, 0.60633609, 0.98543305, 0.85901539, 0.50026039,
       0.54858038, 0.32811122, 0.41344722, 0.40298717, 0.85793878,
       0.14958229, 0.14161885, 0.20358156, 0.44849821, 0.7876557 ,
       0.03202867, 0.03663116, 0.36555741, 0.84818211, 0.77338524,
       0.14424065, 0.11035695, 0.23986322, 0.10956092, 0.73592372,
       0.44296217, 0.77153346, 0.27238372, 0.33286969, 0.155688  ,
       0.24337186, 0.40239367, 0.69303953, 0.43409851, 0.71777

In [4]:
sum(L)

43.54611747465945

In [5]:
np.sum(L)

43.54611747465945

In [6]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

71.9 ms ± 2.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
304 µs ± 7.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
np.min(big_array) 

4.947701235380464e-07

In [8]:
np.max(big_array)

0.999999730891354

In [9]:
big_array.min() #对于np的数组，我们还可以使用 面向对象 的调用方式：object.min(). 但是np.xx()这样的调用方法适用范围更广。

4.947701235380464e-07

In [10]:
big_array.max()

0.999999730891354

In [11]:
big_array.sum()

499488.05311599

In [4]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
np.sum(X) #不管是一维数组 还是 二维矩阵 都是统统sum

120

In [6]:
np.sum(X, axis = 0) #沿着行：想象着一行 里面 有四个人，每个人的任务就是将自己这一列的元素加总。
# （或者想象着将 行 这个维度的压缩掉。行没了）
#区分于之前学的：concatenate，它的axis = 0想象着 一共有x行，每一行的人就是负责将一个A拉过来。

array([24, 28, 32, 36])

In [7]:
A = np.array([[1,2,3],[4,5,6]])
np.concatenate([A,A]) #注意是要写成list形式：【x, y】, 沿着行 axis = 0 的方向拼接

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
np.sum(X, axis = 1) #沿着列：想象着一列 里面 有四个人，每个人的任务就是将自己这一行的元素加总。

array([ 6, 22, 38, 54])

In [16]:
np.prod(X) #所有元素相乘，product，因为有一个元素是0，所以乘积是0.

0

In [17]:
np.prod(X + 1) #支持大数运算，不需要担心整型溢出，+法这里是universal function

20922789888000

In [18]:
np.mean(X)

7.5

In [19]:
np.median(X)

7.5

In [21]:
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [22]:
np.median(v)

2.0

In [24]:
np.percentile(big_array, q = 50) #你会发现，许多np的方法都是：np.func(object)

0.4993248532615271

In [25]:
np.percentile(big_array, q = 100)

0.999999730891354

In [26]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array, q = percent))

4.947701235380464e-07
0.24945615225761406
0.4993248532615271
0.7489482077129004
0.999999730891354


In [27]:
np.var(big_array)

0.08330200673761909

In [28]:
np.std(big_array)

0.2886208702391757

### np.random 总结:
np.random.randint(first, last, size) --> 「first，last）之间的浮点数

np.random.random(size) --> 「0，1）之间的浮点数

np.random.normal(mean, sigma_sqaure, size)

In [29]:
x = np.random.normal(0, 1, size = 1000000)

In [30]:
np.mean(x)

0.0009414745284893437

In [31]:
np.std(x)

1.0011608560211005