In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [5]:
x[3:9] #这个3是index == 3，这个8是index == 8

array([3, 4, 5, 6, 7, 8])

In [6]:
x[3:9:2] #假如说需要的元素满足：每间距2个

array([3, 5, 7])

In [8]:
[x[3], x[5], x[8]] #假如说需要的元素不满足：eg.每间距2个

[3, 5, 8]

In [11]:
ind = [3,5,8] #Fancy Indexing, 向量的fancy indexing
x[ind] #之前x是一个向量，现在x[indx]也是向量

array([3, 5, 8])

In [13]:
ind = np.array([[0,2], [1,3]]) #矩阵的fancy indexing
x[ind] #之前x是一个向量，现在x[indx]是矩阵

array([[0, 2],
       [1, 3]])

In [14]:
X = x.reshape(4, -1) 
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
#现在调用的是在矩阵X中位置为[0,1], [1,2], [2,3]的元素
X[row, col] #之前X是一个矩阵，现在X[row, col]是向量

array([ 1,  6, 11])

In [16]:
X[0, col]

array([1, 2, 3])

In [17]:
X[:2, col] #前两行：第0行，第1行

array([[1, 2, 3],
       [5, 6, 7]])

In [18]:
col = [True, False, True, True]

In [19]:
X[1:3, col] #中间两(2 = 3-1)行：第1行，第2行

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array的比较


In [20]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [22]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [23]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [24]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [25]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [26]:
2 * x == 24 - 4 * x # 2 * 4 == 24 - 16

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [27]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 计算个数

In [29]:
np.sum(x <= 3) #计算有多少个小于3的元素

4

In [30]:
np.count_nonzero(x <= 3)

4

In [31]:
np.any(x == 0) #如果有任意数字是 0, 返回true

True

In [32]:
np.any(x < 0)

False

In [36]:
np.all(x > 0) #因为有一个元素==0，不是>0

False

In [37]:
np.all(x >= 0)

True

In [38]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.sum(X % 2 == 0) #求整个矩阵，有多少个偶数

8

In [40]:
np.sum(X % 2 == 0, axis = 1) #首先X % 2 == 0形成一个true，false矩阵，然后用np.sum(),其中axis = 1说明结果是每一行的。

array([2, 2, 2, 2])

In [42]:
np.sum(X % 2 == 0, axis = 0) #每一列

array([4, 0, 4, 0])

In [44]:
np.all(X > 0, axis = 1) #每一行中，全部都是>0, 注意第一行有一个0，所以第一行是false

array([False,  True,  True,  True])

In [45]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### 与或非：& | ~

In [49]:
np.sum( (x > 3) & (x < 10)) 
#注意不能是并且：&&，而是位与& （因为&&左右需要都是一个true，关键词是一个。但是现在左右都是 数组，而不是一个T/F, 所以需要位与）

6

In [50]:
np.sum( (x % 2 == 0) | (x > 10)) #偶数 或者 大于10的小朋友有多少

11

In [52]:
np.sum(~(x == 0)) #不是==0的小朋友有多少

15

In [53]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [54]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [55]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 应用：在矩阵X中抽出某一行，这一行的最后一个元素能被3整除：

In [57]:
X[X[:,-1] % 3 == 0, :] #byb! 应用：抽出某个房子（样本），它的地理位置为xx（特征）

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

### 补充：
1. Pandas有更加灵活的dataFrame数据结构
2. scikitlearn一般接受的都是numpy的array
3. 所以我们一般是将raw data用Pandas做预处理，然后转化成numpy的array，最后送入scikitlearn