In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [5]:
x[3:9] #这个3是index == 3，这个8是index == 8

array([3, 4, 5, 6, 7, 8])

In [6]:
x[3:9:2] #假如说需要的元素满足：每间距2个

array([3, 5, 7])

In [8]:
[x[3], x[5], x[8]] #假如说需要的元素不满足：eg.每间距2个

[3, 5, 8]

In [11]:
ind = [3,5,8] #Fancy Indexing, 向量的fancy indexing
x[ind] #之前x是一个向量，现在x[indx]也是向量

array([3, 5, 8])

In [13]:
ind = np.array([[0,2], [1,3]]) #矩阵的fancy indexing
x[ind] #之前x是一个向量，现在x[indx]是矩阵

array([[0, 2],
       [1, 3]])

In [14]:
X = x.reshape(4, -1) 
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
#现在调用的是在矩阵X中位置为[0,1], [1,2], [2,3]的元素
X[row, col] #之前X是一个矩阵，现在X[row, col]是向量

array([ 1,  6, 11])